# Generated by Django 4.0.6 on 2026-03-24 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('event_type', models.CharField(choices=[('chess', 'Шахматный турнир'), ('robotics', 'Соревнование по робототехнике'), ('programming', 'Олимпиада по программированию'), ('design', 'Конкурс дизайна'), ('photo', 'Фотоконкурс'), ('other', 'Другое')], max_length=50, verbose_name='Тип события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('registration_deadline', models.DateTimeField(verbose_name='Срок регистрации')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='Максимум участников')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Текущее количество участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('grade', models.CharField(max_length=3, verbose_name='Класс')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('waiting', 'В листе ожидания')], default='pending', max_length=20, verbose_name='Статус')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Отметка о присутствии')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Время отметки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Запись на событие',
                'verbose_name_plural': 'Записи на события',
                'ordering': ['-registration_date'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
