# Generated by Django 4.0.6 on 2026-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кружка')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('icon', models.CharField(default='fas fa-chalkboard', max_length=50, verbose_name='Иконка Font Awesome')),
                ('grade', models.CharField(help_text='Например: 5-11 классы', max_length=100, verbose_name='Классы')),
                ('room', models.CharField(max_length=10, verbose_name='Кабинет')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('schedule', models.JSONField(default=list, help_text='Формат: [{"day": "monday", "time": "15:50-17:30"}, ...]', verbose_name='Расписание')),
                ('days', models.CharField(blank=True, help_text='Дни через запятую: monday,friday', max_length=200, null=True, verbose_name='Дни недели')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Кружок',
                'verbose_name_plural': 'Кружки',
                'ordering': ['order', 'name'],
            },
        ),
    ]
