# Generated by Django 4.0.6 on 2026-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='content',
            field=models.TextField(blank=True, help_text='Вставляйте HTML код', verbose_name='HTML контент страницы'),
        ),
    ]
