# Generated by Django 5.1.6 on 2026-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("chess", "Шахматный турнир"),
                    ("robotics", "Соревнование по робототехнике"),
                    ("programming", "Олимпиада по программированию"),
                    ("photo", "Фотоконкурс"),
                    ("other", "Другое"),
                ],
                max_length=50,
                verbose_name="Тип события",
            ),
        ),
    ]
