# Generated by Django 6.0.4 on 2026-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('chess', 'Шахматный турнир'), ('programming', 'Олимпиада по программированию'), ('photo', 'Фотоконкурс'), ('other', 'Другое')], max_length=50, verbose_name='Тип события'),
        ),
    ]
