# Generated by Django 5.2.1 on 2025-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Class',
            field=models.CharField(default=1, max_length=3, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
