# Generated by Django 5.2.1 on 2025-09-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Class',
        ),
    ]
