# Generated by Django 4.0.6 on 2025-12-23 12:24

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Токен подтверждения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Почта подтверждена'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=accounts.models.UpperField(blank=True, max_length=3, null=True, validators=[accounts.validators.validate_grade_contains], verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия токена'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Токен сброса пароля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
