# Generated by Django 4.0.6 on 2026-03-24 18:11

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, validators=[accounts.validators.validate_russian_name, accounts.validators.validate_special_characters, accounts.validators.validate_capital_first_letter, accounts.validators.validate_no_spaces], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, validators=[accounts.validators.validate_russian_name, accounts.validators.validate_special_characters, accounts.validators.validate_capital_first_letter, accounts.validators.validate_no_spaces], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(max_length=150, validators=[accounts.validators.validate_russian_name, accounts.validators.validate_special_characters, accounts.validators.validate_capital_first_letter, accounts.validators.validate_no_spaces], verbose_name='Отчество'),
        ),
    ]
