# Generated by Django 5.2.1 on 2025-09-10 13:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='users/default_avatar.svg', upload_to=accounts.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
