# Generated by Django 5.2.1 on 2025-09-23 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('active', models.CharField(choices=[('Робототехника, старшая группа', 'Робототехника, старшая группа'), ('Геоинформатика', 'Геоинформатика'), ('Робототехника, младшая группа', 'Робототехника, младшая группа'), ('Промышленный дизайн', 'Промышленный дизайн'), ('Виртуальная и дополненная реальность', 'Виртуальная и дополненная реальность'), ('Программирование', 'Программирование'), ('Фото и видиосъёмка', 'Фото и видиосъёмка'), ('Шахматы', 'Шахматы'), ('ОБЖ', 'ОБЖ')], max_length=50, verbose_name='Кружок')),
                ('Class', models.CharField(max_length=3, verbose_name='Класс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'active')},
            },
        ),
    ]
