# Generated by Django 4.2.16 on 2024-11-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('active', models.CharField(max_length=20)),
                ('clas', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['id'],
            },
        ),
    ]
