# Generated by Django 4.0.6 on 2026-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(max_length=50, verbose_name='Кружок'),
        ),
    ]
