# Generated by Django 4.2.16 on 2025-02-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_profile_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='clas',
            new_name='_class',
        ),
    ]
