# Generated by Django 4.2.16 on 2025-02-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_profile_options_rename_clas_profile__class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_class',
            new_name='Class',
        ),
    ]
