# Generated by Django 6.0 on 2026-04-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_profile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(max_length=50, verbose_name='Кружок'),
        ),
    ]
