# Generated by Django 4.2.16 on 2025-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename__class_profile_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(choices=[('Робототехника, старшая группа', 'Робототехника, старшая группа'), ('Геоинформатика', 'Геоинформатика'), ('Робототехника, младшая группа', 'Робототехника, младшая группа'), ('Промышленный дизайн', 'Промышленный дизайн'), ('Виртуальная и дополненная реальность', 'Виртуальная и дополненная реальность'), ('Программирование', 'Программирование'), ('Фото и видиосъёмка', 'Фото и видиосъёмка'), ('Шахматы', 'Шахматы'), ('ОБЖ', 'ОБЖ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
