# Generated by Django 4.0.6 on 2026-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_circle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='days',
            field=models.CharField(blank=True, help_text='Дни недели через запятую: (например) monday,friday<br>monday-Понедельник<br>tuesday-Вторник<br>wednesday-Среда<br>thursday-Четверг<br>friday-Пятница<br>saturday-Суббота<br>sunday-Воскресенье', max_length=200, null=True, verbose_name='Дни недели'),
        ),
    ]
