# Generated by Django 4.0.6 on 2026-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа'),
        ),
    ]
