"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

#Настройки

import os
from pathlib import Path
from dotenv import load_dotenv
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = BASE_DIR / '.env'
load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = [os.getenv('HOST1'), os.getenv('HOST2'), os.getenv('HOST3')]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'students.apps.StudentsConfig',
    'news.apps.NewsConfig',
    'events.apps.EventsConfig',
    'circles.apps.CirclesConfig',
    'feedback.apps.FeedbackConfig',
    'gallery.apps.GalleryConfig',
    'django_cleanup',
]

UNFOLD = {
    "SITE_TITLE": "Точка Роста — Админ-панель",
    "SITE_HEADER": "Точка Роста",
    "SITE_URL": "/",

    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("Images/main-icon.svg"),
        },
    ],

    "SITE_ICON": "/static/Images/main-icon.svg",
    "SITE_LOGO": "/static/Images/main-icon.svg",   
    "SITE_LOGO_DARK": "/static/Images/main-icon.svg", 

    "DARK_MODE": True,                
    "DEFAULT_THEME": "auto",          


    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,

    "FILTERS": {
        "auto_complete": True,
        "datetime": True,
        "numeric": True,
        "text": True,
    },
}

# JAZZMIN_SETTINGS = {
#     "site_brand": "Точка Роста",  
#     "site_title": "Панель управления Точка Роста",
#     "site_header": "Точка Роста",
#     "welcome_sign": "Добро пожаловать в админ-панель Точки Роста",
#     "copyright": "Точка Роста © 2026",
#     "site_logo": "Images/main-icon.svg",
#     "site_logo_classes": "img-circle",
#     "site_icon": "Images/main-icon.svg",
#     "show_theme_chooser": True,     
#     "icons": {
#         "auth.User": "fas fa-users",
#         "auth.Group": "fas fa-users-cog",
#         "events.Event": "fas fa-calendar-alt",
#         "students.Profile": "fas fa-user-graduate",
#         "circles.Circle": "fas fa-chalkboard",
#         "feedback.Feedback": "fas fa-envelope",
#     },
# }

# JAZZMIN_UI_TWEAKS = {
#     "theme": "flatly",              
#     "dark_mode_theme": "darkly",    
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'blog_project.middleware.AdminAccessMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog_project.context_processors.admin_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE')

TIME_ZONE = os.getenv('TIME_ZONE')

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
if DEBUG:
        STATICFILES_DIRS = [
            os.path.join(BASE_DIR, 'static')
       ]
else:
        STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

AUTH_USER_MODEL = 'accounts.CustomUser'
ADMIN_ENABLED = False

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    #'django.contrib.auth.backends.ModelBackend',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
SITE_URL = os.getenv('SITE_URL')